"""git backend: one private gitconfig per checkout, bound to its exact gitdir."""

from __future__ import annotations

import re
from pathlib import Path

from ..fsutil import SafeWriter, tilde
from ..config import config_dir
from ..profiles import Profile
from ..workspaces import Workspace, git_output, known_workspaces


def context_gitconfig_path(profile: Profile, home: Path) -> Path:
    return home / f".gitconfig-{profile.name}"


def parse_sections(text: str) -> list[tuple[str | None, list[str]]]:
    """Split a gitconfig into (header, body lines), preserving raw text."""
    sections: list[tuple[str | None, list[str]]] = []
    header: str | None = None
    body: list[str] = []
    for line in text.splitlines():
        if line.lstrip().startswith("["):
            sections.append((header, body))
            header, body = line, []
        else:
            body.append(line)
    sections.append((header, body))
    return [s for s in sections if s[0] is not None or s[1]]


def _serialize_sections(sections: list[tuple[str | None, list[str]]]) -> str:
    out: list[str] = []
    for header, body in sections:
        if header is not None:
            out.append(header)
        out.extend(body)
    return "\n".join(out).rstrip("\n") + "\n"


def gitdir_pattern(profile: Profile) -> str:
    """gitdir pattern, keeping ~ when the root lives under home."""
    root = tilde(profile.root_path)
    if not root.endswith("/"):
        root += "/"
    return root


def render_includeif_block(gitdir: str, include_path: str) -> str:
    return f'[includeIf "gitdir:{gitdir}"]\n\tpath = {include_path}\n'


def remove_includeif(gitconfig_text: str, gitdir: str) -> str:
    """Drop the includeIf block for this gitdir, preserving everything else."""
    pattern = re.compile(
        r'\[includeIf\s+"gitdir:' + re.escape(gitdir) + r'"\]\s*\n(\s*path\s*=.*\n?)?',
        re.IGNORECASE,
    )
    return pattern.sub("", gitconfig_text)


def render_workspace_gitconfig(profile: Profile, workspace: Workspace) -> str:
    """Render only the Git and SSH providers enabled for this workspace."""
    selected = set(workspace.providers)
    lines = ["# Generated by aparta, workspace: " + workspace.name]
    if "git" in selected:
        lines.append("[user]")
        if profile.git_name:
            lines.append(f"\tname = {profile.git_name}")
        lines.append(f"\temail = {profile.git_email}")
    if "ssh" in selected and profile.ssh_key:
        lines.extend(
            [
                "[core]",
                f"\tsshCommand = ssh -i {profile.ssh_key} -o IdentitiesOnly=yes",
            ]
        )
    if "ssh" in selected and profile.ssh_alias:
        lines.extend(
            [
                f'[url "git@{profile.ssh_alias}:"]',
                f"\tinsteadOf = https://{profile.git_host}/",
                f"\tinsteadOf = git@{profile.git_host}:",
            ]
        )
    return "\n".join(lines) + "\n"


def _absolute_gitdir(repo: Path) -> str | None:
    return git_output("rev-parse", "--absolute-git-dir", repo=repo)


def _without_managed_includes(
    text: str,
    profiles: dict[str, Profile],
    home: Path,
) -> str:
    """Remove old broad and previously generated exact Aparta include blocks."""
    context_paths: set[str] = set()
    for profile in profiles.values():
        path = context_gitconfig_path(profile, home)
        context_paths.update({str(path), tilde(path)})
    generated_dir = config_dir() / "git"
    generated_roots = {str(generated_dir.resolve()), tilde(generated_dir)}
    kept: list[tuple[str | None, list[str]]] = []
    for header, body in parse_sections(text):
        is_include = bool(header and header.lstrip().lower().startswith("[includeif "))
        paths = []
        if is_include:
            for line in body:
                match = re.match(r"^\s*path\s*=\s*(.+?)\s*$", line, re.IGNORECASE)
                if match:
                    paths.append(match.group(1))
        managed = any(
            value in context_paths
            or any(
                value == root or value.startswith(root.rstrip("/") + "/")
                for root in generated_roots
            )
            for value in paths
        )
        if not managed:
            kept.append((header, body))
    return _serialize_sections(kept) if kept else ""


def remove_legacy_local_includes(
    repos: list[Path],
    profiles: dict[str, Profile],
    writer: SafeWriter,
    home: Path,
) -> None:
    """Remove Aparta's old shared local includes from adopted repositories."""
    managed = {str(context_gitconfig_path(profile, home)) for profile in profiles.values()}
    for repo in repos:
        current = git_output("config", "--local", "--get-all", "include.path", repo=repo) or ""
        for value in set(current.splitlines()).intersection(managed):
            if writer.dry_run:
                writer.changes.append(f"[dry-run] git -C {repo} config --local --unset-all include.path {value}")
                continue
            git_output("config", "--local", "--unset-all", "include.path", value, repo=repo)


def reconcile_workspace_git(
    profiles: dict[str, Profile],
    workspaces: dict[str, Workspace],
    writer: SafeWriter,
    home: Path | None = None,
) -> None:
    """Bind every known checkout's Git and SSH identity to its exact gitdir."""
    home = home or Path.home()
    candidates = known_workspaces(profiles, workspaces)
    gitconfig = home / ".gitconfig"
    existing = gitconfig.read_text() if gitconfig.exists() else ""
    user_config = _without_managed_includes(existing, profiles, home)
    exact_blocks: list[str] = []

    for repo, workspace in sorted(candidates.items(), key=lambda item: str(item[0])):
        selected = set(workspace.providers)
        if not selected.intersection({"git", "ssh"}):
            continue
        profile = profiles[workspace.profile]
        generated = workspace.gitconfig_path
        writer.write_text(generated, render_workspace_gitconfig(profile, workspace))
        gitdir = _absolute_gitdir(repo)
        if gitdir:
            include_path = tilde(generated) if home == Path.home() else str(generated)
            exact_blocks.append(render_includeif_block(gitdir, include_path).rstrip())

    if exact_blocks:
        blocks = "\n\n".join(exact_blocks)
        middle = user_config.strip("\n")
        merged = blocks + ("\n\n" + middle if middle else "") + "\n\n" + blocks + "\n"
    else:
        merged = user_config

    if merged != existing:
        writer.write_text(gitconfig, merged)
    remove_legacy_local_includes(list(candidates), profiles, writer, home)


def global_user_name() -> str:
    """user.name from the global git config, a sensible default for new profiles."""
    return git_output("config", "--global", "user.name", timeout=10) or ""
