"""git backend: per-profile gitconfig plus an includeIf merged into ~/.gitconfig."""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
from pathlib import Path

from ..i18n import _
from . import Note

from ..fsutil import SafeWriter, tilde
from ..config import config_dir
from ..profiles import Profile
from ..workspaces import (
    Workspace,
    git_workspace_root,
    implicit_workspace,
    profile_for_path,
)


def context_gitconfig_path(profile: Profile, home: Path) -> Path:
    return home / f".gitconfig-{profile.name}"


def render_context_gitconfig(profile: Profile) -> str:
    """Render the contents of ~/.gitconfig-<profile>."""
    lines = ["# Generated by aparta, profile: " + profile.name, "[user]"]
    if profile.git_name:
        lines.append(f"\tname = {profile.git_name}")
    lines.append(f"\temail = {profile.git_email}")
    if profile.ssh_key:
        key = profile.ssh_key
        lines += [
            "[core]",
            f'\tsshCommand = ssh -i {key} -o IdentitiesOnly=yes',
        ]
    if profile.ssh_alias:
        host = profile.git_host
        lines += [
            f'[url "git@{profile.ssh_alias}:"]',
            f"\tinsteadOf = https://{host}/",
            f"\tinsteadOf = git@{host}:",
        ]
    return "\n".join(lines) + "\n"


def _parse_sections(text: str) -> list[tuple[str | None, list[str]]]:
    """Split a gitconfig into (header, body lines), preserving raw text."""
    sections: list[tuple[str | None, list[str]]] = []
    header: str | None = None
    body: list[str] = []
    for line in text.splitlines():
        if line.lstrip().startswith("["):
            sections.append((header, body))
            header, body = line, []
        else:
            body.append(line)
    sections.append((header, body))
    return [s for s in sections if s[0] is not None or s[1]]


def _serialize_sections(sections: list[tuple[str | None, list[str]]]) -> str:
    out: list[str] = []
    for header, body in sections:
        if header is not None:
            out.append(header)
        out.extend(body)
    return "\n".join(out).rstrip("\n") + "\n"


def _section_index(sections: list[tuple[str | None, list[str]]], name: str) -> int | None:
    for i, (header, _body) in enumerate(sections):
        if header and re.match(rf"^\s*\[{re.escape(name)}\]\s*$", header, re.IGNORECASE):
            return i
    return None


def _set_key(sections: list[tuple[str | None, list[str]]], section: str, key: str, value: str) -> None:
    """Update the key in place when present, otherwise append it to the section."""
    line = f"\t{key} = {value}"
    index = _section_index(sections, section)
    if index is None:
        sections.append((f"[{section}]", [line]))
        return
    header, body = sections[index]
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=", re.IGNORECASE)
    for i, existing in enumerate(body):
        if pattern.match(existing):
            body[i] = line
            return
    insert_at = len(body)
    while insert_at > 0 and not body[insert_at - 1].strip():
        insert_at -= 1
    body.insert(insert_at, line)


def _set_url_insteadof(sections: list[tuple[str | None, list[str]]], alias: str, host: str) -> None:
    """Point the host's insteadOf block at the alias, updating an old one."""
    header = f'[url "git@{alias}:"]'
    body = [f"\tinsteadOf = https://{host}/", f"\tinsteadOf = git@{host}:"]
    for i, (existing_header, existing_body) in enumerate(sections):
        if existing_header and existing_header.lstrip().lower().startswith("[url "):
            text = "\n".join(existing_body)
            if f"https://{host}/" in text or f"git@{host}:" in text:
                sections[i] = (header, body)
                return
    sections.append((header, body))


def merge_context_gitconfig(existing_text: str, profile: Profile) -> str:
    """Merge the profile's settings into an existing gitconfig."""
    if not existing_text.strip():
        return render_context_gitconfig(profile)

    sections = _parse_sections(existing_text)
    if profile.git_name:
        _set_key(sections, "user", "name", profile.git_name)
    _set_key(sections, "user", "email", profile.git_email)
    if profile.ssh_key:
        _set_key(sections, "core", "sshCommand", f"ssh -i {profile.ssh_key} -o IdentitiesOnly=yes")
    if profile.ssh_alias:
        _set_url_insteadof(sections, profile.ssh_alias, profile.git_host)
    return _serialize_sections(sections)


def gitdir_pattern(profile: Profile) -> str:
    """gitdir pattern, keeping ~ when the root lives under home."""
    root = tilde(profile.root_path)
    if not root.endswith("/"):
        root += "/"
    return root


def render_includeif_block(gitdir: str, include_path: str) -> str:
    return f'[includeIf "gitdir:{gitdir}"]\n\tpath = {include_path}\n'


def has_includeif(gitconfig_text: str, gitdir: str) -> bool:
    """Whether an includeIf block for this gitdir already exists."""
    pattern = re.compile(
        r'\[includeIf\s+"gitdir:' + re.escape(gitdir) + r'"\]', re.IGNORECASE
    )
    return bool(pattern.search(gitconfig_text))


def merge_includeif(gitconfig_text: str, gitdir: str, include_path: str) -> str:
    """Append the includeIf block only if absent; preserve everything else."""
    if has_includeif(gitconfig_text, gitdir):
        return gitconfig_text
    block = render_includeif_block(gitdir, include_path)
    if gitconfig_text and not gitconfig_text.endswith("\n"):
        gitconfig_text += "\n"
    sep = "\n" if gitconfig_text else ""
    return gitconfig_text + sep + block


def remove_includeif(gitconfig_text: str, gitdir: str) -> str:
    """Drop the includeIf block for this gitdir, preserving everything else."""
    pattern = re.compile(
        r'\[includeIf\s+"gitdir:' + re.escape(gitdir) + r'"\]\s*\n(\s*path\s*=.*\n?)?',
        re.IGNORECASE,
    )
    return pattern.sub("", gitconfig_text)


def workspace_gitconfig_path(workspace: Workspace) -> Path:
    """Private generated Git config for one canonical checkout path."""
    digest = hashlib.sha256(str(workspace.root_path).encode()).hexdigest()[:20]
    return config_dir() / "git" / f"workspace-{digest}.gitconfig"


def render_workspace_gitconfig(profile: Profile, workspace: Workspace) -> str:
    """Render only the Git and SSH providers enabled for this workspace."""
    selected = set(workspace.providers)
    lines = ["# Generated by aparta, workspace: " + workspace.name]
    if "git" in selected:
        lines.append("[user]")
        if profile.git_name:
            lines.append(f"\tname = {profile.git_name}")
        lines.append(f"\temail = {profile.git_email}")
    if "ssh" in selected and profile.ssh_key:
        lines.extend(
            [
                "[core]",
                f"\tsshCommand = ssh -i {profile.ssh_key} -o IdentitiesOnly=yes",
            ]
        )
    if "ssh" in selected and profile.ssh_alias:
        lines.extend(
            [
                f'[url "git@{profile.ssh_alias}:"]',
                f"\tinsteadOf = https://{profile.git_host}/",
                f"\tinsteadOf = git@{profile.git_host}:",
            ]
        )
    return "\n".join(lines) + "\n"


def _git_location_env() -> dict[str, str]:
    """Resolve a checkout without honoring a caller's repository redirection."""
    env = dict(os.environ)
    for key in ("GIT_DIR", "GIT_WORK_TREE", "GIT_COMMON_DIR"):
        env.pop(key, None)
    return env


def _absolute_gitdir(repo: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--absolute-git-dir"],
            env=_git_location_env(),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def _without_managed_includes(
    text: str,
    profiles: dict[str, Profile],
    home: Path,
) -> str:
    """Remove old broad and previously generated exact Aparta include blocks."""
    context_paths: set[str] = set()
    for profile in profiles.values():
        path = context_gitconfig_path(profile, home)
        context_paths.update({str(path), tilde(path)})
    generated_dir = config_dir() / "git"
    generated_roots = {str(generated_dir.resolve()), tilde(generated_dir)}
    kept: list[tuple[str | None, list[str]]] = []
    for header, body in _parse_sections(text):
        is_include = bool(header and header.lstrip().lower().startswith("[includeif "))
        paths = []
        if is_include:
            for line in body:
                match = re.match(r"^\s*path\s*=\s*(.+?)\s*$", line, re.IGNORECASE)
                if match:
                    paths.append(match.group(1))
        managed = any(
            value in context_paths
            or any(
                value == root or value.startswith(root.rstrip("/") + "/")
                for root in generated_roots
            )
            for value in paths
        )
        if not managed:
            kept.append((header, body))
    return _serialize_sections(kept) if kept else ""


def _workspace_candidates(
    profiles: dict[str, Profile],
    workspaces: dict[str, Workspace],
) -> dict[Path, Workspace]:
    """All known checkouts, with explicit records overriding legacy ownership."""
    from ..discovery import find_repos

    candidates: dict[Path, Workspace] = {}
    for profile in profiles.values():
        repos = find_repos(profile.root_path) + [
            Path(raw).expanduser() for raw in profile.adopted_repos
        ]
        for repo in repos:
            root = git_workspace_root(repo)
            if root is None:
                continue
            owner = profile_for_path(root, profiles)
            if owner is not None:
                candidates[root] = implicit_workspace(root, owner)
    for workspace in workspaces.values():
        root = git_workspace_root(workspace.root_path)
        if root is not None and workspace.profile in profiles:
            candidates[root] = Workspace(
                workspace.name,
                str(root),
                workspace.profile,
                list(workspace.providers),
            )
    return candidates


def _remove_legacy_local_includes(
    repos: list[Path],
    profiles: dict[str, Profile],
    writer: SafeWriter,
    home: Path,
) -> None:
    """Remove Aparta's old shared local includes from adopted repositories."""
    managed = {str(context_gitconfig_path(profile, home)) for profile in profiles.values()}
    for repo in repos:
        try:
            current = subprocess.run(
                ["git", "-C", str(repo), "config", "--local", "--get-all", "include.path"],
                env=_git_location_env(),
                capture_output=True,
                text=True,
                timeout=30,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        for value in set(current.stdout.splitlines()).intersection(managed):
            if writer.dry_run:
                writer.changes.append(
                    f"[dry-run] git -C {repo} config --local --unset-all include.path {value}"
                )
                continue
            subprocess.run(
                ["git", "-C", str(repo), "config", "--local", "--unset-all", "include.path", value],
                env=_git_location_env(),
                capture_output=True,
                text=True,
                timeout=30,
            )


def reconcile_workspace_git(
    profiles: dict[str, Profile],
    workspaces: dict[str, Workspace],
    writer: SafeWriter,
    home: Path | None = None,
) -> None:
    """Bind every known checkout's Git and SSH identity to its exact gitdir."""
    home = home or Path.home()
    candidates = _workspace_candidates(profiles, workspaces)
    gitconfig = home / ".gitconfig"
    existing = gitconfig.read_text() if gitconfig.exists() else ""
    user_config = _without_managed_includes(existing, profiles, home)
    exact_blocks: list[str] = []

    for repo, workspace in sorted(candidates.items(), key=lambda item: str(item[0])):
        selected = set(workspace.providers)
        if not selected.intersection({"git", "ssh"}):
            continue
        profile = profiles[workspace.profile]
        generated = workspace_gitconfig_path(workspace)
        writer.write_text(generated, render_workspace_gitconfig(profile, workspace))
        gitdir = _absolute_gitdir(repo)
        if gitdir:
            include_path = tilde(generated) if home == Path.home() else str(generated)
            exact_blocks.append(render_includeif_block(gitdir, include_path).rstrip())

    if exact_blocks:
        blocks = "\n\n".join(exact_blocks)
        middle = user_config.strip("\n")
        merged = blocks + ("\n\n" + middle if middle else "") + "\n\n" + blocks + "\n"
    else:
        merged = user_config

    if merged != existing:
        writer.write_text(gitconfig, merged)
    _remove_legacy_local_includes(list(candidates), profiles, writer, home)


def apply_git(
    profile: Profile,
    writer: SafeWriter,
    home: Path | None = None,
    register_root: bool = True,
) -> list[Note]:
    """Write ~/.gitconfig-<profile> and merge its includeIf into ~/.gitconfig."""
    home = home or Path.home()
    ctx_path = context_gitconfig_path(profile, home)
    existing_ctx = ctx_path.read_text() if ctx_path.exists() else ""
    writer.write_text(ctx_path, merge_context_gitconfig(existing_ctx, profile))

    if not register_root:
        return []

    gitconfig = home / ".gitconfig"
    existing = gitconfig.read_text() if gitconfig.exists() else ""
    include_path = tilde(ctx_path) if home == Path.home() else str(ctx_path)
    merged = merge_includeif(existing, gitdir_pattern(profile), include_path)
    if merged != existing:
        writer.write_text(gitconfig, merged)

    return apply_adopted_git(profile, writer, home)


def apply_adopted_git(profile: Profile, writer: SafeWriter, home: Path | None = None) -> list[Note]:
    """Adopted repos include the profile's gitconfig locally, without moving folders."""
    notes: list[Note] = []
    if not profile.adopted_repos:
        return notes
    home = home or Path.home()
    include = str(context_gitconfig_path(profile, home))
    for raw in profile.adopted_repos:
        repo = Path(raw).expanduser()
        if not (repo / ".git").exists():
            notes.append(Note("warn", _("[yellow]warning:[/yellow] {repo} is not a git repository; skipping.", repo=repo)))
            continue
        current = subprocess.run(
            ["git", "-C", str(repo), "config", "--local", "--get-all", "include.path"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if include in current.stdout.splitlines():
            continue
        if writer.dry_run:
            notes.append(Note(
                "info",
                f"[yellow]--dry-run[/yellow] git -C {repo} config --local --add include.path {include}",
            ))
            continue
        r = subprocess.run(
            ["git", "-C", str(repo), "config", "--local", "--add", "include.path", include],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if r.returncode != 0:
            notes.append(Note("error", _("[red]adopting {repo} failed:[/red] {error}", repo=repo, error=r.stderr.strip())))
        else:
            notes.append(Note("info", _("[green]git:[/green] {repo} adopted by profile '{name}'", repo=repo.name, name=profile.name)))
    return notes
