"""git backend: per-profile gitconfig plus an includeIf merged into ~/.gitconfig."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from rich.console import Console

from ..fsutil import SafeWriter, tilde
from ..profiles import Profile

console = Console()


def context_gitconfig_path(profile: Profile, home: Path) -> Path:
    return home / f".gitconfig-{profile.name}"


def render_context_gitconfig(profile: Profile) -> str:
    """Render the contents of ~/.gitconfig-<profile>."""
    lines = ["# Generated by aparta, profile: " + profile.name, "[user]"]
    if profile.git_name:
        lines.append(f"\tname = {profile.git_name}")
    lines.append(f"\temail = {profile.git_email}")
    if profile.ssh_key:
        key = profile.ssh_key
        lines += [
            "[core]",
            f'\tsshCommand = ssh -i {key} -o IdentitiesOnly=yes',
        ]
    if profile.ssh_alias:
        host = profile.git_host
        lines += [
            f'[url "git@{profile.ssh_alias}:"]',
            f"\tinsteadOf = https://{host}/",
            f"\tinsteadOf = git@{host}:",
        ]
    return "\n".join(lines) + "\n"


def gitdir_pattern(profile: Profile) -> str:
    """gitdir pattern, keeping ~ when the root lives under home."""
    root = tilde(profile.root_path)
    if not root.endswith("/"):
        root += "/"
    return root


def render_includeif_block(gitdir: str, include_path: str) -> str:
    return f'[includeIf "gitdir:{gitdir}"]\n\tpath = {include_path}\n'


def has_includeif(gitconfig_text: str, gitdir: str) -> bool:
    """Whether an includeIf block for this gitdir already exists."""
    pattern = re.compile(
        r'\[includeIf\s+"gitdir:' + re.escape(gitdir) + r'"\]', re.IGNORECASE
    )
    return bool(pattern.search(gitconfig_text))


def merge_includeif(gitconfig_text: str, gitdir: str, include_path: str) -> str:
    """Append the includeIf block only if absent; preserve everything else."""
    if has_includeif(gitconfig_text, gitdir):
        return gitconfig_text
    block = render_includeif_block(gitdir, include_path)
    if gitconfig_text and not gitconfig_text.endswith("\n"):
        gitconfig_text += "\n"
    sep = "\n" if gitconfig_text else ""
    return gitconfig_text + sep + block


def apply_git(profile: Profile, writer: SafeWriter, home: Path | None = None) -> None:
    """Write ~/.gitconfig-<profile> and merge its includeIf into ~/.gitconfig."""
    home = home or Path.home()
    ctx_path = context_gitconfig_path(profile, home)
    writer.write_text(ctx_path, render_context_gitconfig(profile))

    gitconfig = home / ".gitconfig"
    existing = gitconfig.read_text() if gitconfig.exists() else ""
    include_path = tilde(ctx_path) if home == Path.home() else str(ctx_path)
    merged = merge_includeif(existing, gitdir_pattern(profile), include_path)
    if merged != existing:
        writer.write_text(gitconfig, merged)

    apply_adopted_git(profile, writer, home)


def apply_adopted_git(profile: Profile, writer: SafeWriter, home: Path | None = None) -> None:
    """Adopted repos (outside root): the local .git/config includes the
    profile's gitconfig, inheriting e-mail/key/insteadOf without moving."""
    if not profile.adopted_repos:
        return
    home = home or Path.home()
    include = str(context_gitconfig_path(profile, home))
    for raw in profile.adopted_repos:
        repo = Path(raw).expanduser()
        if not (repo / ".git").exists():
            console.print(f"[yellow]aviso:[/yellow] {repo} não é um repositório git; pulando.")
            continue
        current = subprocess.run(
            ["git", "-C", str(repo), "config", "--local", "--get-all", "include.path"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if include in current.stdout.splitlines():
            continue  # already adopted
        if writer.dry_run:
            console.print(
                f"[yellow]--dry-run[/yellow] git -C {repo} config --local --add include.path {include}"
            )
            continue
        r = subprocess.run(
            ["git", "-C", str(repo), "config", "--local", "--add", "include.path", include],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if r.returncode != 0:
            console.print(f"[red]adoção de {repo} falhou:[/red] {r.stderr.strip()}")
        else:
            console.print(f"[green]git:[/green] {repo.name} adotado pelo perfil '{profile.name}'")
