"""The per-profile gitconfig is merged, never regenerated from scratch."""

from __future__ import annotations

from aparta.backends.git import merge_context_gitconfig
from aparta.profiles import Profile

HANDWRITTEN = """\
[user]
\tname = Ana Dev
\temail = old@acme.com
[core]
\t# personal GitHub account over port 443
\tsshCommand = ssh -i ~/.ssh/old_key -o IdentitiesOnly=yes
[commit]
\tgpgsign = true
[alias]
\tst = status
"""

PROFILE = Profile(
    name="acme",
    root="~/work/acme",
    git_email="ana@acme.com",
    ssh_key="/home/ana/.ssh/id_ed25519_acme",
)


def test_merge_keeps_unmanaged_sections_and_comments():
    out = merge_context_gitconfig(HANDWRITTEN, PROFILE)
    assert "gpgsign = true" in out
    assert "st = status" in out
    assert "# personal GitHub account over port 443" in out


def test_merge_keeps_the_user_name():
    out = merge_context_gitconfig(HANDWRITTEN, PROFILE)
    assert "name = Ana Dev" in out


def test_merge_updates_managed_keys():
    out = merge_context_gitconfig(HANDWRITTEN, PROFILE)
    assert "email = ana@acme.com" in out
    assert "old@acme.com" not in out
    assert "sshCommand = ssh -i /home/ana/.ssh/id_ed25519_acme -o IdentitiesOnly=yes" in out
    assert "old_key" not in out


def test_profile_name_overrides_the_existing_one():
    named = Profile(**{**PROFILE.__dict__, "git_name": "Ana at Acme"})
    out = merge_context_gitconfig(HANDWRITTEN, named)
    assert "name = Ana at Acme" in out
    assert "name = Ana Dev" not in out


def test_alias_block_is_updated_not_duplicated():
    existing = HANDWRITTEN + '[url "git@github.com-old:"]\n\tinsteadOf = https://github.com/\n'
    aliased = Profile(**{**PROFILE.__dict__, "ssh_alias": "github.com-acme"})
    out = merge_context_gitconfig(existing, aliased)
    assert out.count("[url ") == 1
    assert '[url "git@github.com-acme:"]' in out
    assert "insteadOf = https://github.com/" in out
    assert "insteadOf = git@github.com:" in out


def test_other_hosts_keep_their_own_alias_block():
    existing = HANDWRITTEN + '[url "git@gitlab.com-work:"]\n\tinsteadOf = https://gitlab.com/\n'
    aliased = Profile(**{**PROFILE.__dict__, "ssh_alias": "github.com-acme"})
    out = merge_context_gitconfig(existing, aliased)
    assert '[url "git@gitlab.com-work:"]' in out
    assert '[url "git@github.com-acme:"]' in out


def test_empty_input_renders_from_scratch():
    out = merge_context_gitconfig("", PROFILE)
    assert out.startswith("# Generated by aparta")
    assert "email = ana@acme.com" in out


def test_merge_is_idempotent():
    once = merge_context_gitconfig(HANDWRITTEN, PROFILE)
    twice = merge_context_gitconfig(once, PROFILE)
    assert once == twice
