"""opencode adapter: a shell.env plugin in <repo>/.opencode/plugins/.

opencode has no env field in opencode.json; the supported way to inject
environment into its shell commands and tool calls is the plugin hook
"shell.env" (anomalyco/opencode PR #12012). aparta owns the generated
plugin file and merges variables into it on re-apply.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..fsutil import SafeWriter
from .base import AgentAdapter, missing_keys

_HEADER = "// Generated by aparta. Edit values through `aparta apply`.\n"
_LINE = re.compile(r'output\.env\["([^"]+)"\] = "([^"]*)";')


def parse_plugin_env(text: str) -> dict[str, str]:
    return {m.group(1): m.group(2) for m in _LINE.finditer(text)}


def render_plugin(env: dict[str, str]) -> str:
    lines = "\n".join(
        f'    output.env["{k}"] = "{v.replace(chr(34), chr(92) + chr(34))}";'
        for k, v in sorted(env.items())
    )
    return (
        _HEADER
        + "export const ApartaEnv = async () => ({\n"
        + '  "shell.env": async (_input, output) => {\n'
        + lines
        + "\n  },\n});\n"
    )


class OpencodeAdapter(AgentAdapter):
    name = "opencode"
    display_name = "opencode"

    def plugin_path(self, repo: Path) -> Path:
        return repo / ".opencode" / "plugins" / "aparta-env.js"

    def detect(self, repo: Path) -> bool:
        return True  # the plugins dir is created on demand; always applicable

    def inject(self, repo: Path, env: dict[str, str], writer: SafeWriter) -> bool:
        path = self.plugin_path(repo)
        current = parse_plugin_env(path.read_text()) if path.exists() else {}
        return writer.write_text(path, render_plugin({**current, **env}))

    def validate(self, repo: Path, env: dict[str, str]) -> tuple[bool, str]:
        path = self.plugin_path(repo)
        if not path.exists():
            return False, "plugin aparta-env.js ausente"
        missing = missing_keys(parse_plugin_env(path.read_text()), env)
        return (not missing, "env ok" if not missing else f"faltando: {', '.join(missing)}")

    def read_env(self, repo: Path) -> dict[str, str]:
        path = self.plugin_path(repo)
        return parse_plugin_env(path.read_text()) if path.exists() else {}
