"""opencode adapter: a shell.env plugin in <repo>/.opencode/plugins/.

opencode has no env field in opencode.json; the supported way to inject
environment into its shell commands and tool calls is the plugin hook
"shell.env" (anomalyco/opencode PR #12012). aparta owns the generated
plugin file and merges variables into it on re-apply.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..i18n import _
from ..fsutil import SafeWriter
from .base import CHECK_COMMAND, AgentAdapter, missing_keys

_HEADER = "// Generated by aparta. Edit values through `aparta apply`.\n"
_LINE = re.compile(r'output\.env\["([^"]+)"\] = "([^"]*)";')


def parse_plugin_env(text: str) -> dict[str, str]:
    return {m.group(1): m.group(2) for m in _LINE.finditer(text)}


def render_plugin(env: dict[str, str], with_check: bool = False) -> str:
    """The generated plugin: env for shells, plus an optional credential check.

    opencode has no session.start event, but the plugin body itself runs at
    bootstrap, and session.created covers new sessions.
    """
    lines = "\n".join(
        f'    output.env["{k}"] = "{v.replace(chr(34), chr(92) + chr(34))}";'
        for k, v in sorted(env.items())
    )
    if not with_check:
        return (
            _HEADER
            + "export const ApartaEnv = async () => ({\n"
            + '  "shell.env": async (_input, output) => {\n'
            + lines
            + "\n  },\n});\n"
        )
    return (
        _HEADER
        + "export const ApartaEnv = async ({ client, $ }) => {\n"
        + "  const check = async () => {\n"
        + "    try {\n"
        + "      const out = await $`" + CHECK_COMMAND + "`.text().catch((e) => e.stdout ?? \"\");\n"
        + "      if (out.trim() && client.tui?.showToast) {\n"
        + '        await client.tui.showToast({ body: { message: out.trim(), variant: "error" } });\n'
        + "      }\n"
        + "    } catch {}\n"
        + "  };\n"
        + "  await check();\n"
        + "  return {\n"
        + '    "shell.env": async (_input, output) => {\n'
        + lines
        + "\n    },\n"
        + "    event: async ({ event }) => {\n"
        + '      if (event.type === "session.created") await check();\n'
        + "    },\n"
        + "  };\n"
        + "};\n"
    )


class OpencodeAdapter(AgentAdapter):
    name = "opencode"
    display_name = "opencode"

    def plugin_path(self, repo: Path) -> Path:
        return repo / ".opencode" / "plugins" / "aparta-env.js"

    def detect(self, repo: Path) -> bool:
        return True  # the plugins dir is created on demand; always applicable

    def inject(self, repo: Path, env: dict[str, str], writer: SafeWriter) -> bool:
        path = self.plugin_path(repo)
        existing = path.read_text() if path.exists() else ""
        current = parse_plugin_env(existing) if existing else {}
        # keep whatever mode the file is already in
        return writer.write_text(
            path, render_plugin({**current, **env}, with_check=CHECK_COMMAND in existing)
        )

    def install_check(self, repo: Path, writer: SafeWriter) -> bool:
        path = self.plugin_path(repo)
        existing = path.read_text() if path.exists() else ""
        if CHECK_COMMAND in existing:
            return False
        return writer.write_text(
            path, render_plugin(parse_plugin_env(existing), with_check=True)
        )

    def uninstall_check(self, repo: Path, writer: SafeWriter) -> bool:
        path = self.plugin_path(repo)
        if not path.exists() or CHECK_COMMAND not in path.read_text():
            return False
        env = parse_plugin_env(path.read_text())
        if env:
            return writer.write_text(path, render_plugin(env, with_check=False))
        return writer.remove_file(path)

    def validate(self, repo: Path, env: dict[str, str]) -> tuple[bool, str]:
        path = self.plugin_path(repo)
        if not path.exists():
            return False, _("aparta-env.js plugin missing")
        missing = missing_keys(parse_plugin_env(path.read_text()), env)
        return (not missing, _("env ok") if not missing else _("missing: {keys}", keys=", ".join(missing)))

    def remove_env(self, repo: Path, keys: list[str], writer: SafeWriter) -> bool:
        path = self.plugin_path(repo)
        if not path.exists():
            return False
        current = parse_plugin_env(path.read_text())
        remaining = {k: v for k, v in current.items() if k not in keys}
        if remaining == current:
            return False
        if remaining:
            return writer.write_text(path, render_plugin(remaining))
        return writer.remove_file(path)

    def read_env(self, repo: Path) -> dict[str, str]:
        path = self.plugin_path(repo)
        return parse_plugin_env(path.read_text()) if path.exists() else {}
